package main.java.avramenko.view;

public enum Activities {
    SHOW_MAIN_MENU,
    SHOW_MAIN_MENU_AND_CREATE,
    SHOW_CATALOG,
    ADD_BOOK,
    DELETE_BOOK,
    SHOW_READERS,
    ADD_READER,
    DELETE_READER,
    MANAGE_AND_CREATE,
    MANAGE_ORDERS,
    SHOW_ORDERS,
    MAKE_AN_ORDER,
    RETURN_BOOK,
    ADD_TO_BLACK_LIST,
    SHOW_BLACK_LIST,
    EXIT
}
